# ======
# Video
# ======
vo=gpu-next
hwdec=videotoolbox
target-prim=display-p3
target-trc=srgb
target-contrast=1224
target-colorspace-hint=no
treat-srgb-as-power22=no
video-sync=display-resample
scale=ewa_lanczos
#linear-upscaling=yes
sigmoid-upscaling=yes
#scale-antiring=0.5
dscale=mitchell
correct-downscaling=yes
linear-downscaling=yes
#dscale-antiring=0.5
cscale=ewa_lanczos
dither-depth=no
#interpolation=yes
tscale=oversample
deband-iterations=3
deband-threshold=42
deband-range=12
deband-grain=24
hr-seek=yes
#hr-seek-framedrop=yes
#cache-pause=no
demuxer-max-bytes=500MiB
demuxer-max-back-bytes=200MiB

# ======
# Audio
# ======
replaygain=track
replaygain-fallback=-5
audio-file-auto=fuzzy
alang=chi,ko,jpn,eng

# =========
# Subtitle
# =========
#sid=no
sub-auto=fuzzy
sub-file-paths-append=ass:srt:sub:subs:subtitles #"path"
slang=eng
subs-fallback=yes
sub-use-margins=no
sub-scale-by-window=yes
sub-scale-with-window=yes
blend-subtitles=yes
secondary-sub-pos=0

# =========
# Playlist
# =========
#shuffle=yes
#loop-playlist=yes
autocreate-playlist=same  #filter - to include everthing in the filter below
directory-filter-types=video,audio,image
#directory-mode=lazy
image-display-duration=inf
screenshot-png-compression=9
#screenshot-tag-colorspace=no
save-watch-history=yes
save-position-on-quit=yes
watch-later-options=start,speed,volume,audio-delay,panscan,aid,vid,sid,sub-delay,sub-ass-override,inverse-tone-mapping

# =======
# Window
# =======
fs=yes
#native-fs=no
autofit=73%x73% #1920x1080
border=no
osc=no
osd-bar=no
osd-duration=2000
#keep-open=yes

# ======
# Paths
# ======
icc-cache-dir="~~/cache/icc"
gpu-shader-cache-dir="~~/cache/shaders"
watch-later-dir="~~/cache/watch_later"
watch-history-path="~~/cache/watch_history.jsonl"
#use-filedir-conf=yes
#input-builtin-bindings=no
input-conf="~~/mess.conf"
include="~~/styles.conf"
include="~~/profiles.conf"
#log-file="~~/cache/mpv.log"
#msg-level=all=v