[protocol.https]
profile-restore=copy
cookies=yes
cookies-file=~/.config/mpv/cache/scripts/cookies.txt
force-seekable=yes
demuxer-max-bytes=60M
demuxer-max-back-bytes=50M

[jpg-fix]
#profile-cond=filename:match("%.jpe?g$") ~= nil
profile-restore=copy
vf-add=format=colorlevels=limited

[Gif]
profile-cond=get("duration", math.huge) <= 10
profile-restore=copy
loop=inf

[MV]
profile-cond=p.path and (p.path:find("/Music/") or (p.duration and p.duration < 100))
profile-restore=copy
#video=no
video-sync=display-desync
script-opts-append=skip_intro-enabled=no
watch-later-options=volume,audio-delay,panscan,aid,sid,sub-delay,sub-ass-override,inverse-tone-mapping

[spatial-audio]
profile-cond=p["audio-params/channel-count"] > 2
profile-restore=copy
ao=avfoundation

[HDR]
profile-cond=p["video-params/gamma"] == "pq" or p["video-params/gamma"] == "hlg"
profile-restore=copy
#icc-profile=/Users/mahmoud/.config/mpv/icc/TRC.icc
icc-use-luma=yes
target-peak=500
target-lut=""
lut=""
# [DTM] #
tone-mapping=bt.2446a
hdr-compute-peak=yes
hdr-peak-percentile=99.995
hdr-peak-decay-rate=100
hdr-scene-threshold-low=4
hdr-scene-threshold-high=16
tone-mapping-max-boost=1.2
gamut-mapping-mode=perceptual

[DolbyVision]
profile-cond=get("video-params/colormatrix") == "dolbyvision" or (filename ~= nil and (filename:lower():find("dovi") ~= nil or filename:lower():find("dolbyvision") ~= nil or filename:lower():find("dolby.vision") ~= nil or filename:lower():match("[%.%-_]dv[%.%-_]") ~= nil))
profile-restore=copy
tone-mapping=spline
hdr-compute-peak=no

[HDR10+]
profile-cond=get("video-params/scene-max-r", 0) > 0
profile-restore=copy
tone-mapping=st2094-40
hdr-compute-peak=no

[4k]
#profile-cond=width >= 3840 or height >= 2160
profile-restore=copy
glsl-shaders-append=~~/shaders/SSimDownscaler.glsl
linear-downscaling=no
dscale-antiring=0

[SD]
profile-cond=p.path and not p.path:find("%vsprocessed%.") and width and height and (width * height) < 1228800
profile-restore=copy
#glsl-shaders-append=~~/shaders/ArtCNN/ArtCNN_C4F16.glsl
deband=yes
sub-gauss=0.8

[SD-Telecine]
profile-cond=string.find(string.match(path or "", "[^/\\]+$") or "", ".tel.", 1, true) ~= nil
profile-restore=copy
vf=lavfi=[fieldmatch=order=auto:combmatch=full,decimate]

[SD-Interlace]
profile-cond=string.find(string.match(path or "", "[^/\\]+$") or "", ".int.", 1, true) ~= nil
profile-restore=copy
vf=lavfi=[bwdif=mode=1:deint=interlaced]

[SD-mix_N_mash]
profile-cond=string.find(string.match(path or "", "[^/\\]+$") or "", ".mix.", 1, true) ~= nil
profile-restore=copy
vf=lavfi=[fieldmatch=order=auto:combmatch=full,bwdif=mode=0:deint=interlaced,decimate]

[Anime4K]
profile-restore=copy
glsl-shaders-append=~~/shaders/Anime4K/Anime4K_Clamp_Highlights.glsl
glsl-shaders-append=~~/shaders/Anime4K/Anime4K_Restore_CNN_M.glsl
glsl-shaders-append=~~/shaders/Anime4K/Anime4K_Upscale_CNN_x2_M.glsl
glsl-shaders-append=~~/shaders/Anime4K/Anime4K_AutoDownscalePre_x2.glsl
deband=yes

[FSRCNNX]
profile-restore=copy
glsl-shaders-append=~~/shaders/FSRCNNX/FSRCNNX_x2_16-0-4-1.glsl

[ArtCNN]
profile-restore=copy
glsl-shaders-append=~~/shaders/ArtCNN/ArtCNN_C4F16.glsl

[KrigBilateral]
profile-restore=copy
glsl-shaders-append=~~/shaders/KrigBilateral.glsl

[Inverse-TM]
profile-restore=copy
inverse-tone-mapping=yes
target-peak=500
hdr-compute-peak=no

[battery]
profile-restore=copy
video-sync=audio
scale=spline36
#linear-upscaling=no
sigmoid-upscaling=no
dscale=spline36
correct-downscaling=no
#linear-downscaling=no
cscale=spline36
interpolation=no
deband=no
hr-seek=no
#blend-subtitles=no
glsl-shaders=""