# Absolute paths to tools for macOS Homebrew
ffmpeg_path=/opt/homebrew/bin/ffmpeg
alass_path=/opt/homebrew/bin/alass

# Preferred synchronization engine: 'alass', 'ffsubsync', or 'ask'
audio_subsync_tool=alass
altsub_subsync_tool=alass

# Unload original subtitles after syncing (yes, no)
unload_old_sub=yes