show_on_pause=no
seek_handle_size=0
FORCE_fix_not_ontop=no
scale_windowed=1.3
scale_fullscreen=1.8

download_path=~/Downloads
title_youtube_stats=no
show_description=no
show_youtube_comments=no
comments_path="~/.config/mpv/cache/scripts/comments"
download_button=yes
show_file_size=yes
ytdl_format="bv*[height<=1440][format_note!*=?AI-upscaled]+ba/b[height<=1440]/bv*+ba/b"