show_on_pause=no
seek_handle_size=0
FORCE_fix_not_ontop=no
scale_windowed=1.4
scale_fullscreen=1.8
download_path=~/Downloads

#show_description=no
#show_youtube_comments=no
#title_youtube_stats=no
show_file_size=yes
download_button=yes