show_on_pause=no
seek_handle_size=0
FORCE_fix_not_ontop=no
scale_windowed=1.4
scale_fullscreen=1.8
download_path=~/Downloads

show_description=no
show_youtube_comments=no
title_youtube_stats=no
show_file_size=no
download_button=yes

osc_color=#000000
window_title_color=#FFFFFF
window_controls_color=#d4baff
window_controls_close_hover=#ff7096
window_controls_minmax_hover=#9b5de5
title_color=#FFFFFF
seekbarfg_color=#9b5de5
seekbarbg_color=#2e1b4d
seekbar_cache_color=#7350aa
volumebar_match_seek_color=no
time_color=#f0e6ff
chapter_title_color=#d4baff
chapter_marker_color=#a682ff
chapter_marker_current_color=#9b5de5
side_buttons_color=#d4baff
middle_buttons_color=#f0e6ff
playpause_color=#9b5de5
held_element_color=#7350aa
hover_effect_color=#FFFFFF
thumbnail_border_color=#a682ff
thumbnail_border_outline=#FFFFFF